# 通过修改为国内镜像源提高国内访问速度
# * 阿里云源：https://developer.aliyun.com/mirror/pypi
# * TUNA 源：https://mirrors.tuna.tsinghua.edu.cn/help/pypi/
# * USTC 源：https://mirrors.ustc.edu.cn/help/pypi.html

[global]
index-url = http://mirrors.aliyun.com/pypi/simple/

[install]
trusted-host=mirrors.aliyun.com
